language: go

env:
  - OPERATOR_SDK_VERSION=v0.8.1

services:
  - docker

install:
  # dep
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
  - make test

before_deploy:
  # chmod
  - sudo apt-get install -y coreutils
  # operator-sdk
  - curl -OJL https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu && \
    chmod +x operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu && \
    sudo mv operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk

deploy:
  provider: script
  skip_cleanup: true
  # environment variables defined in travis ui
  script: bash .travis/docker_push.sh $TRAVIS_TAG $DOCKER_PASSWORD
  on:
    tags: true
