language: go

services:
  - docker

install:
  # dep
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
  - make test

before_deploy:
  - .travis/install_operator_sdk.sh

deploy:
  provider: script
  skip_cleanup: true
  # environment variables defined in travis ui
  script: bash .travis/docker_push.sh $TRAVIS_TAG $DOCKER_PASSWORD
  on:
    tags: true
