apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: lastpass.niqdev.com
spec:
  group: niqdev.com
  scope: Namespaced
  version: v1alpha1
  names:
    kind: LastPass
    listKind: LastPassList
    plural: lastpass
    singular: lastpass
  subresources:
    status: {}
  validation:
    # https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject
    openAPIV3Schema:
      properties:
        # https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          required:
            - secretRef
          properties:
            secretRef:
              type: object
              required:
                - name
              properties:
                group:
                  type: string
                name:
                  type: string
                withUsername:
                  type: boolean
                withPassword:
                  type: boolean
                withUrl:
                  type: boolean
                withNote:
                  type: boolean
