apiVersion: apps/v1
kind: Deployment
metadata:
  name: lastpass-operator
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: lastpass-operator
  template:
    metadata:
      labels:
        name: lastpass-operator
    spec:
      serviceAccountName: lastpass-operator
      containers:
        - name: lastpass-operator
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          command:
          - lastpass-operator
          imagePullPolicy: Always
          env:
            # default
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "lastpass-operator"
            # custom
            - name: LASTPASS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lastpass-master-secret
                  key: username
            - name: LASTPASS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lastpass-master-secret
                  key: password
